baseURL: "https://blog.zchary.cn"
languageCode: "en-us"
title: "Zchary's blog"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-R55X0MJ64S

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Zchary's blog
  description: "Web dev related | share lives"
  keywords: [Blog, Portfolio, Golang, NodeJS, Backend, Geek, TypeScript]
  author: "Zchary"
  images: ["avatar.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  utteranc:
    enable: true
    repo: Zchary-ma/Comments
    issueTerm: pathname
    theme: github-light

  assets:
    disableHLJS: true
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    #   text: 'Home'
    icon: "avatar.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "assets/images/avatar.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: a passion-driven developer.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/zcharyMa"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/12715116"
    - name: github
      url: "https://github.com/zchary-ma"
    - name: RSS
      url: "index.xml"

  analytics:
    google:
      SiteVerificationTag: "G-R55X0MJ64S"
    baidu:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/Zchary-Ma/blog/edit/master/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
    - identifier: archives
      name: archives
      url: /archives/
      weight: 40
    - identifier: projects
      name: projects
      url: /projects/
      weight: 50
    - identifier: about
      name: about
      url: /about/
      weight: 5
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
  highlight:
    # anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    style: monokai
    # noClasses: true
    tabWidth: 4

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON
